### ISSUE TITLE
[Feature Request] Persistent Data

### ISSUE THREAD

**Issue by I-am-Kamino** [luketainton/hesk-docker#9]
Hi,
I am not sure if posting this here is right, as I am new to github. Please correct mistakes made.

### My request

So there are several things:
- When redeploying the container I always need to install/upgrade again, which is troublesome when there isn't actually an update. -> Updating only works when the installed version is newer then the one registered in the database. (May be an issue to Hesk itself).
- I have to download my language pack into the container again.
- I need to edit my presets e.g. `/srv/language/<locale>/emails/<preset>.txt` and `/srv/hesk_settings.inc.php`

This all takes some time so I am wondering if you may persist some of these settings. Maybe using environment variables or a conf.yml.

### My configuration
I currently use your hesk image using docker-compose and mariadb.
My docker-compose.yml looks like this:
```
version: '3.9'
services:
  hesk-mariadb:
    hostname: hesk-mariadb
    container_name: hesk-mariadb
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=<rpw>
      - MARIADB_USER=hesk
      - MARIADB_PASSWORD=<upw>
      - MARIADB_DATABASE=hesk
      - MARIADB_SKIP_TEST_DB=yes
    volumes:
      - '/opt/helpdesk/mariadb_data:/bitnami/mariadb'
    networks:
      - proxy
  hesk:
    image: ghcr.io/luketainton/hesk:latest
    hostname: hesk
    container_name: hesk
    depends_on:
      - hesk-mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hesk-support.entrypoints=http"
      - "traefik.http.routers.hesk-support.rule=Host(`helpdesk.domain.tld`)"
      - "traefik.http.middlewares.hesk-support-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hesk-support.middlewares=hesk-support-https-redirect"
      - "traefik.http.routers.hesk-support-secure.entrypoints=https"
      - "traefik.http.routers.hesk-support-secure.rule=Host(`helpdesk.domain.tld`)"
      - "traefik.http.routers.hesk-support-secure.tls=true"
      - "traefik.http.routers.hesk-support-secure.tls.certresolver=http"
      - "traefik.http.services.hesk-support.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      
networks:
  proxy:
    external: true
```

Best regards,
Kamino

**Comment by luketainton** [comment]
Hi @I-am-Kamino!

Thanks for the feature request. For the following points:
- _I have to download my language pack into the container again._
- _I need to edit my presets e.g. /srv/language/<locale>/emails/<preset>.txt and /srv/hesk_settings.inc.php_

I'd suggest downloading the language pack and creating these preset files on your host, and volume-mounting them into the container. I'll see if there's a better way to do this in the meantime.

I'll look into why you keep getting asked to re-install it.

**Comment by Gitoffomalawn** [comment]
Hi @luketainton. I'd like to second @I-am-Kamino's request, and add some info. Hopefully this wall of text will be of some help to you both.

### The issue
I'm experiencing similar issues to @I-am-Kamino. If, for some reason, I have to recreate the HESK container, it forces me to go through the install process again. Only it can't complete it, since the database already exists. Updating doesn't work either, because the script responsible for updating refers to the default HESK login values for the already-existing database. It then errors out with the following message if you've changed any of those values (which you should):
```
Fatal error: Uncaught mysqli_sql_exception: No such file or directory in /srv/install/install_functions.inc.php:105 Stack trace: #0 /srv/install/install_functions.inc.php(105): mysqli_connect('localhost', 'test', 'test', 'hesk') #1 /srv/install/update.php(87): hesk_iTestDatabaseConnection(true) #2 {main} thrown in /srv/install/install_functions.inc.php on line 105
```
### What didn't work
The `/srv` directory seems to be the one where all the HESK files live. This is, incidentally, also where in the `install` directory lives that needs to be removed after installation. There's also a `themes` folder, which is where you'd add any new HESK themes you'd want to use. In short, i'd like to be able to mount the whole `/srv/ directory as a persistent volume in order to make life a little easier. I've tried adding the following to my `docker-compose.yml` file under the hesk container section in an effort to persist data:
```
    volumes:
      - ./config:/srv
```
However, this creates an empty directory without any of the necessary files after spinning up the containers.

### What worked
Eventually, I got it to work by going through the following steps:

1. Clone this repo and `cd` into the directory.
2. Edit the `docker-compose.example.yml` file so that it looks like the one at the bottom of this post, plus any other things you'd like to add. Save it as `docker-compose.yml`.
3. Create the directory you're going to use as persistent volume with `mkdir` (in my case: `config` in the local directory).
4. Copy the contents of the `hesk` directory in the repo to the directory created in the previous step.
5. Give global access (`chmod 777`) to the directory from step 3, and all files within it. If you don't do this, HESK will complain that PHP cannot write to certain directories. I didn't have the time to try and ferret out all affected directories in order to selctively set permissions, so I opted for the stupid and easy option.
6. Execute `docker-compose up -d`
7. Go through the installation steps as you normally would. At the end of installation, remove the installation directory from the directory created in step 3.
8. HESK should work fine now, and persist through recreated containers without reinstalling. You can use the directory from step 3 to add themes, edit files, or do any other things you'd like to do.

### My `docker-compose.yml` file
```
version: "3"
services:
  db:
    image: mariadb:10.7
    container_name: hesk_db
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: <DB_NAME>
      MARIADB_USER: <HESK_USER>
      # Please change the password before deploying.
      MARIADB_PASSWORD: <PASSWORD>

  hesk:
    depends_on:
      - db
    image: ghcr.io/luketainton/hesk:latest
    container_name: hesk
    volumes:
      - ./config:/srv
    ports:
      - "80:80"
    restart: unless-stopped
```
